import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage } from "pdf-lib";

const OUT = join(process.cwd(), "tmp", "c1r19");
mkdirSync(OUT, { recursive: true });

// 1x1 PNG (red) for embedding as rasterized figure / scanned page.
function pngRed(): Uint8Array {
  // minimal valid PNG (1x1) generated by hand is fragile; use a base64 1x1 red png.
  const b64 =
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";
  return new Uint8Array(Buffer.from(b64, "base64"));
}

async function addFigureAndTableText(page: PDFPage, font: PDFFont, yStart: number) {
  page.drawText("Figura 1 - exemplo de figura nativa", { x: 40, y: yStart, size: 11, font });
  page.drawText("Tabela 1 - exemplo de tabela", { x: 40, y: yStart - 40, size: 11, font });
  page.drawText("1 2 3", { x: 40, y: yStart - 60, size: 11, font });
  page.drawText("4 5 6", { x: 40, y: yStart - 75, size: 11, font });
}

async function build() {
  const font = await (await PDFDocument.create()).embedFont(StandardFonts.Helvetica);
  const results: Record<string, number> = {};

  // --- native digital PDF (text) ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([595, 842]);
    p.drawText("Universidade Federal de Lavras", { x: 40, y: 800, size: 14, font });
    p.drawText("Titulo de teste acentuacao ção ãõ é", { x: 40, y: 780, size: 12, font });
    await addFigureAndTableText(p, font, 700);
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_native.pdf"), buf);
    results.ext_native = buf.length;
  }

  // --- scanned PDF (image-only page, no text layer) ---
  {
    const d = await PDFDocument.create();
    const png = await d.embedPng(pngRed());
    const p = d.addPage([595, 842]);
    p.drawImage(png, { x: 0, y: 0, width: 595, height: 842 });
    // also embed a png as a "figure"
    const p2 = d.addPage([595, 842]);
    p2.drawText("Figura 1 - pagina escaneada", { x: 40, y: 800, size: 12, font });
    p2.drawImage(png, { x: 100, y: 400, width: 300, height: 300 });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_scanned.pdf"), buf);
    results.ext_scanned = buf.length;
  }

  // --- hybrid PDF (text + image) ---
  {
    const d = await PDFDocument.create();
    const png = await d.embedPng(pngRed());
    const p = d.addPage([595, 842]);
    p.drawText("Texto hibrido com figura embutida", { x: 40, y: 800, size: 12, font });
    p.drawImage(png, { x: 100, y: 400, width: 200, height: 200 });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_hybrid.pdf"), buf);
    results.ext_hybrid = buf.length;
  }

  // --- landscape page ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([842, 595]);
    p.drawText("Pagina em paisagem", { x: 40, y: 540, size: 12, font });
    await addFigureAndTableText(p, font, 460);
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_landscape.pdf"), buf);
    results.ext_landscape = buf.length;
  }

  // --- mixed orientation (portrait + landscape) ---
  {
    const d = await PDFDocument.create();
    const p1 = d.addPage([595, 842]);
    p1.drawText("Retrato", { x: 40, y: 800, size: 12, font });
    const p2 = d.addPage([842, 595]);
    p2.drawText("Paisagem", { x: 40, y: 540, size: 12, font });
    const p3 = d.addPage([595, 842]);
    p3.drawText("Retrato denovo", { x: 40, y: 800, size: 12, font });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_mixed_orient.pdf"), buf);
    results.ext_mixed_orient = buf.length;
  }

  // --- many images (50 figures on pages) ---
  {
    const d = await PDFDocument.create();
    const png = await d.embedPng(pngRed());
    for (let i = 0; i < 10; i++) {
      const p = d.addPage([595, 842]);
      p.drawText(`Figura ${i + 1} - bloco de figuras`, { x: 40, y: 800, size: 12, font });
      for (let j = 0; j < 5; j++) {
        p.drawImage(png, { x: 40 + (j % 2) * 280, y: 600 - Math.floor(j / 2) * 180, width: 200, height: 150 });
      }
    }
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_many_images.pdf"), buf);
    results.ext_many_images = buf.length;
  }

  // --- only figures (no tables, no body text) ---
  {
    const d = await PDFDocument.create();
    const png = await d.embedPng(pngRed());
    const p = d.addPage([595, 842]);
    p.drawText("Figura 1 - so figura", { x: 40, y: 800, size: 12, font });
    p.drawImage(png, { x: 100, y: 300, width: 300, height: 300 });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_only_figures.pdf"), buf);
    results.ext_only_figures = buf.length;
  }

  // --- only tables (no figures) ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([595, 842]);
    p.drawText("Tabela 1 - so tabela", { x: 40, y: 800, size: 12, font });
    p.drawText("A B C", { x: 40, y: 780, size: 11, font });
    p.drawText("1 2 3", { x: 40, y: 765, size: 11, font });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_only_tables.pdf"), buf);
    results.ext_only_tables = buf.length;
  }

  // --- no figures, no tables (pure text) ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([595, 842]);
    p.drawText("Introducao. Este documento nao tem figuras nem tabelas.", { x: 40, y: 800, size: 12, font });
    p.drawText("Metodologia. Texto apenas para teste de robustez.", { x: 40, y: 780, size: 12, font });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_no_fig_no_tab.pdf"), buf);
    results.ext_no_fig_no_tab = buf.length;
  }

  // --- tiny PDF (very small page) ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([50, 50]);
    p.drawText("x", { x: 5, y: 40, size: 8, font });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_tiny.pdf"), buf);
    results.ext_tiny = buf.length;
  }

  // --- grayscale (no color) - draw with gray rgb ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([595, 842]);
    p.drawText("Tons de cinza (sem cor)", { x: 40, y: 800, size: 12, font, color: rgb(0.3, 0.3, 0.3) });
    p.drawRectangle({ x: 40, y: 600, width: 100, height: 100, color: rgb(0.5, 0.5, 0.5) });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_grayscale.pdf"), buf);
    results.ext_grayscale = buf.length;
  }

  // --- unicode rare + multilingual (WinAnsi-safe subset: acentos + alemão/francês/espanhol) ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([595, 842]);
    p.drawText("Acentos: çãõ é à Ü Ö ñ ß ¿ ¡", { x: 40, y: 800, size: 12, font });
    p.drawText("Multilingue: English Deutsch Français Español Português", { x: 40, y: 780, size: 12, font });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_unicode_ml.pdf"), buf);
    results.ext_unicode_ml = buf.length;
  }

  // --- duplicate pages ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([595, 842]);
    p.drawText("Pagina duplicada A", { x: 40, y: 800, size: 12, font });
    const p2 = d.addPage([595, 842]);
    p2.drawText("Pagina duplicada A", { x: 40, y: 800, size: 12, font });
    const p3 = d.addPage([595, 842]);
    p3.drawText("Pagina duplicada A", { x: 40, y: 800, size: 12, font });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_dup_pages.pdf"), buf);
    results.ext_dup_pages = buf.length;
  }

  // --- with embedded file attachment ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([595, 842]);
    p.drawText("Documento com anexo", { x: 40, y: 800, size: 12, font });
    d.attach(new Uint8Array(Buffer.from("conteudo do anexo de teste")), "anexo.txt", { mimeType: "text/plain" });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_with_attachment.pdf"), buf);
    results.ext_with_attachment = buf.length;
  }

  // --- transparency (alpha) ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([595, 842]);
    p.drawText("Transparencia", { x: 40, y: 800, size: 12, font });
    p.drawRectangle({ x: 40, y: 600, width: 200, height: 200, color: rgb(1, 0, 0), opacity: 0.3 });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_transparency.pdf"), buf);
    results.ext_transparency = buf.length;
  }

  // --- extreme compression (useObjectStreams true is default; force small) ---
  {
    const d = await PDFDocument.create();
    const p = d.addPage([595, 842]);
    let s = "Introducao. ";
    for (let i = 0; i < 500; i++) s += "palavra repete ";
    p.drawText(s, { x: 40, y: 800, size: 10, font });
    const buf = await d.save({ useObjectStreams: true });
    writeFileSync(join(OUT, "ext_compressed.pdf"), buf);
    results.ext_compressed = buf.length;
  }

  // --- no metadata (omit info dict) ---
  {
    const d = await PDFDocument.create();
    (d as any).title = undefined;
    const p = d.addPage([595, 842]);
    p.drawText("Sem metadados", { x: 40, y: 800, size: 12, font });
    const buf = await d.save();
    writeFileSync(join(OUT, "ext_no_metadata.pdf"), buf);
    results.ext_no_metadata = buf.length;
  }

  console.log("FIXTURES:", JSON.stringify(results, null, 0));
}

build().then(() => process.exit(0)).catch((e) => { console.error("FATAL", e); process.exit(1); });
