import { AcademicFields, WorkTypeValue, isAdvisorRequired, isCpgWork, isResearchProject, isUflaCollectionWork } from "./ufla-rules";
import { validateReferencesText } from "./references-validator";
import { ACADEMIC_PRODUCTION_INITIAL_SUPPORT_NOTICE, academicProductionTypeById } from "./academic-production-types";
import { detectAbstractTopicConflict, detectCpgForbiddenStructures, detectControlledPlaceholder, detectGenericAiLikeText, detectPlaceholderText, detectProgramConflict } from "./academic-guardrails";
import { assessAbstractHeuristics, assessResumoHeuristics } from "./text-diagnostics";
import { hasSufficientImpactIndicators } from "./impact-indicators";

export type ValidationSeverity = "error" | "warning" | "info";
export interface ValidationIssue { severity: ValidationSeverity; code: string; message: string; what?: string; why?: string; action?: string; }
export interface AdherenceCategory { key: string; label: string; status: "implemented" | "partial" | "pending" | "manual"; statusLabel: string; note?: string; }

export const ADHERENCE_CATEGORIES: AdherenceCategory[] = [
  { key: "metadata", label: "Metadados", status: "implemented", statusLabel: "Implementado", note: "Tipo de trabalho, autor, título, orientador e campos básicos são editáveis." },
  { key: "pretextual", label: "Elementos pré-textuais", status: "partial", statusLabel: "Parcial", note: "Capa, folha de rosto, resumo e abstract são gerados quando o tipo de trabalho exige esses elementos." },
  { key: "resumo", label: "Resumo", status: "partial", statusLabel: "Parcial", note: "Estrutura e campo são gerados. Validação de extensão, parágrafo único e palavras-chave está implementada como alerta." },
  { key: "abstract", label: "Abstract", status: "partial", statusLabel: "Parcial", note: "Estrutura e campo são gerados. Validação de extensão, parágrafo único e keywords está implementada como alerta." },
  { key: "keywords", label: "Palavras-chave", status: "implemented", statusLabel: "Implementado", note: "Campo editável com validação de quantidade e separação por ponto e vírgula." },
  { key: "body", label: "Corpo do texto", status: "implemented", statusLabel: "Implementado", note: "Editor com títulos, citações longas, negrito e itálico. Espaçamento 1,5 aplicado no DOCX." },
  { key: "illustrations", label: "Ilustrações e tabelas", status: "partial", statusLabel: "Parcial", note: "Imagens importadas são preservadas como marcadores. Legendas e fontes devem ser conferidas manualmente." },
  { key: "references", label: "Referências", status: "partial", statusLabel: "Parcial", note: "Normalização de destaque (negrito) implementada com detecção de tipo. Itens ambíguos exigem revisão manual." },
  { key: "posttextual", label: "Elementos pós-textuais", status: "partial", statusLabel: "Parcial", note: "Referências, apêndices e anexos são suportados. Glossário e índice não foram implementados." },
  { key: "export", label: "Exportação DOCX", status: "implemented", statusLabel: "Implementado", note: "Gera DOCX editável com margens, fonte, espaçamento e sumário atualizável. PDF deve ser gerado externamente." },
  { key: "research-project", label: "Projeto de pesquisa / NBR 15287", status: "partial", statusLabel: "Parcial", note: "Suporte inicial para projeto de pesquisa com estrutura básica e validações parciais. A revisão final pelo usuário é obrigatória." },
];

function hasValue(value: string | WorkTypeValue): boolean { return value.trim().length > 0; }
function isSimpleArticle(fields: AcademicFields): boolean { return fields.workType === "artigo"; }
function normalizeForValidation(value: string): string { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase().replace(/\s+/g, " ").trim(); }
function wordCount(value: string): number { return value.trim().split(/\s+/).filter(Boolean).length; }
function paragraphCount(value: string): number { return value.split(/\n{2,}/).map((p) => p.trim()).filter(Boolean).length; }
function keywordItems(value: string): string[] { return value.split(/[;\.]/).map((i) => i.trim()).filter(Boolean); }
function stripHeadingSyntax(value: string): string { return normalizeForValidation(value).replace(/^#+\s*/, "").replace(/^\d+(?:\.\d+)*\s+/, "").replace(/[:.\-–—]+$/, "").trim(); }
function hasSectionHeading(editorText: string, labels: string[]): boolean { const targets = labels.map(normalizeForValidation); return editorText.split(/\n+/).map(stripHeadingSyntax).some((l) => targets.includes(l)); }
function push(issues: ValidationIssue[], severity: ValidationSeverity, code: string, message: string, what?: string, why?: string, action?: string): void { issues.push({ severity, code, message, what, why, action }); }

function addPlaceholderIssues(fields: AcademicFields, editorText: string, issues: ValidationIssue[]): void {
  const critical: [string, string][] = [["Título", fields.title], ["Autor", fields.author], ["Programa", fields.program], ["Curso", fields.course], ["Natureza do trabalho", fields.workNature], ["Resumo", fields.resumo], ["Abstract", fields.abstractText], ["Indicadores de impacto", fields.indicadoresImpacto]];
  if (isAdvisorRequired(fields.workType)) critical.push(["Orientador", fields.advisor]);
  for (const [label, value] of critical) if (hasValue(value) && detectPlaceholderText(value)) { push(issues, "error", "placeholder-detected", "Há marcador de preenchimento no documento.", `O campo ${label} contém placeholder ou instrução não substituída.`, "O DOCX final não pode conter campos genéricos ou instruções de preenchimento.", "Substitua o trecho por informação real antes da versão final."); break; }
  const auxiliary: [string, string][] = [["Subtítulo", fields.subtitle], ["Introdução", fields.introducao], ["Conclusão", fields.conclusao], ["Palavras-chave", fields.palavrasChave], ["Keywords", fields.keywords], ["Agradecimentos", fields.agradecimentos], ["Dedicatória", fields.dedicatoria]];
  for (const [label, value] of auxiliary) if (hasValue(value) && detectPlaceholderText(value)) { push(issues, "warning", "placeholder-detected", "Há marcador de preenchimento no documento.", `O campo ${label} contém placeholder ou instrução não substituída.`, "O DOCX final não pode conter campos genéricos ou instruções de preenchimento.", "Substitua o trecho por informação real antes da versão final."); break; }
  if (hasValue(editorText) && detectControlledPlaceholder(editorText)) push(issues, "error", "draft-placeholder-detected", "O rascunho ainda contém campos a preencher.", "O texto principal contém marcadores controlados de rascunho como [PREENCHER: ...].", "O DOCX final não pode conter marcadores de preenchimento; eles indicam seções não redigidas.", "Substitua os marcadores por conteúdo real antes de gerar a versão final.");
  else if (hasValue(editorText) && detectPlaceholderText(editorText)) push(issues, "warning", "placeholder-detected", "Há marcador de preenchimento no documento.", "O texto principal contém placeholder ou instrução não substituída.", "O DOCX final não pode conter campos genéricos ou instruções de preenchimento.", "Substitua o trecho por informação real antes da versão final.");
}

function addCriticalMetadataIssues(fields: AcademicFields, issues: ValidationIssue[]): void {
  if (isAdvisorRequired(fields.workType) && !hasValue(fields.advisor)) push(issues, "error", "advisor-required", "Informe o orientador antes da versão final.", "O orientador não foi informado.", "Monografias, dissertações e teses exigem nome do orientador na folha de rosto; sem esse dado o DOCX pode sair com marcador de preenchimento.", "Preencha o campo Orientador com o nome completo antes de gerar o DOCX final.");
  if (!hasValue(fields.workNature)) return;
  const normalized = normalizeForValidation(fields.workNature);
  if (/EXIGENCIAS? D[OA] EDUCACAO CIENTIFICA E AMBIENTAL/.test(normalized)) push(issues, "error", "work-nature-malformed", "A natureza do trabalho parece estar incompleta ou gramaticalmente incorreta.", "Foi detectado trecho como 'exigências do Educação Científica e Ambiental'.", "A folha de rosto precisa mencionar corretamente o Programa de Pós-Graduação e a unidade acadêmica.", "Corrija para algo como: 'como parte das exigências do Programa de Pós-Graduação em Educação Científica e Ambiental...'");
  if ((fields.workType === "dissertacao" || fields.workType === "tese") && /PROJETO DE PESQUISA/.test(normalized)) push(issues, "error", "work-type-nature-conflict", "Há conflito entre o tipo selecionado e a natureza do trabalho.", "O tipo selecionado é dissertação/tese, mas a natureza do trabalho diz 'Projeto de pesquisa'.", "Projeto de pesquisa, dissertação e tese possuem estruturas e exigências diferentes.", "Selecione Projeto de pesquisa ou reescreva a natureza como dissertação/tese, conforme o caso real.");
  if (fields.workType === "projeto_pesquisa" && /(DISSERTACAO|TESE) APRESENTADA/.test(normalized)) push(issues, "error", "work-type-nature-conflict", "Há conflito entre o tipo selecionado e a natureza do trabalho.", "O tipo selecionado é projeto de pesquisa, mas a natureza do trabalho diz dissertação/tese.", "Projeto de pesquisa, dissertação e tese possuem estruturas e exigências diferentes.", "Selecione Dissertação/Tese ou reescreva a natureza como projeto de pesquisa, conforme o caso real.");
}

function addProgramConflictIssues(fields: AcademicFields, editorText: string, issues: ValidationIssue[]): void { if (detectProgramConflict(fields, editorText)) push(issues, "error", "program-conflict", "Há conflito entre programa/área informado e texto do documento.", "O documento menciona programas ou áreas diferentes em campos centrais.", "A folha de rosto, resumo e corpo do texto precisam ter metadados institucionais consistentes.", "Revise Programa, Curso, Natureza do trabalho, Resumo, Abstract e texto principal."); }
function addAbstractTopicIssues(fields: AcademicFields, issues: ValidationIssue[]): void { const r = detectAbstractTopicConflict(fields); if (r.conflict) push(issues, r.severity, "abstract-topic-conflict", "O Abstract parece não corresponder ao título/resumo.", "O texto em inglês possui termos centrais incompatíveis com o tema em português.", "Abstract incoerente passa impressão de texto alucinado ou reaproveitado.", "Revise o Abstract e confirme se ele traduz fielmente o resumo."); }
function addGenericAiLikeIssues(fields: AcademicFields, editorText: string, issues: ValidationIssue[]): void { for (const [label, value] of [["Resumo", fields.resumo], ["Abstract", fields.abstractText], ["Introdução", fields.introducao], ["Conclusão", fields.conclusao], ["Texto principal", editorText]] as [string, string][]) if (hasValue(value) && detectGenericAiLikeText(value)) { push(issues, "warning", "generic-ai-like-text", "Possível texto genérico ou com padrão de texto automático detectado.", `O trecho em ${label} contém expressões genéricas ou de 'cara de IA'.`, "Expressões genéricas podem enfraquecer a argumentação acadêmica e a originalidade do texto.", "Reescreva com termos específicos do seu trabalho, evitando clichês de redação automática."); break; } }
function addCpgForbiddenIssues(fields: AcademicFields, editorText: string, issues: ValidationIssue[]): void { if (!isCpgWork(fields.workType)) return; const found = detectCpgForbiddenStructures(editorText); if (found.length) push(issues, "error", "cpg-forbidden-structure", "O texto contém elementos estruturais incompatíveis com o modelo CPG/UFLA.", `Foram detectados: ${found.join(", ")}.`, "Os modelos CPG/UFLA não devem conter capa, folha de rosto, ficha catalográfica, folha de aprovação, sumário ou indicadores de impacto no corpo do texto.", "Remova esses elementos do editor; o CPG exige apenas Resumo, Palavras-chave, Abstract, Keywords e seções textuais."); }

function addTextDiagnosticIssues(fields: AcademicFields, issues: ValidationIssue[]): void {
  if (isCpgWork(fields.workType) || !hasValue(fields.resumo)) return;
  const h = assessResumoHeuristics(fields.resumo);
  if (!h.hasMethod) push(issues, "warning", "resumo-missing-method", "O resumo não parece descrever a metodologia utilizada.", "Não foram detectados termos de método no resumo (ex.: metodologia, análise, observação).", "O resumo deve sintetizar objetivo, método, resultados e conclusão quando aplicável.", "Adicione uma frase sobre a metodologia no campo Resumo.");
  if (!h.hasObjective) push(issues, "warning", "resumo-missing-objective", "O resumo não parece explicitar o objetivo.", "Não foram detectados termos de objetivo no resumo (ex.: objetivo, analisa, investiga).", "O objetivo orienta a leitura e a avaliação do trabalho.", "Adicione o objetivo no campo Resumo.");
  if (!h.hasResult && !h.hasConclusion) push(issues, "warning", "resumo-missing-result-conclusion", "O resumo não parece apresentar resultado ou conclusão.", "Não foram detectados termos de resultado/conclusão no resumo.", "Resumos costumam encerrar com resultados ou conclusão.", "Adicione resultado ou conclusão no campo Resumo.");
  const a = assessAbstractHeuristics(fields);
  if (!a.isEmpty && a.tooMuchPortuguese) push(issues, "warning", "abstract-looks-portuguese", "O abstract parece conter português demais para um texto em inglês.", "Há mais termos em português do que em inglês no campo Abstract.", "O abstract deve estar em inglês ou idioma estrangeiro, traduzindo fielmente o resumo.", "Revise o Abstract e reescreva em inglês, se aplicável.");
  if (!a.isEmpty && !a.looksEnglish && !a.tooMuchPortuguese) push(issues, "info", "abstract-language-review", "Confira se o abstract está em inglês ou idioma estrangeiro.", "O abstract não apresentou marcadores claros de inglês.", "A língua estrangeira deve espelhar o resumo.", "Confira a língua do Abstract antes da versão final.");
}

function addResumoAbstractIssues(fields: AcademicFields, issues: ValidationIssue[]): void {
  if (isCpgWork(fields.workType)) return;
  if (hasValue(fields.resumo)) { const c = wordCount(fields.resumo); if (c < 150 || c > 500) push(issues, "warning", "resumo-word-count", `Resumo com ${c} palavra(s). Confira se está entre 150 e 500 palavras antes da versão final.`); if (paragraphCount(fields.resumo) > 1) push(issues, "warning", "resumo-single-paragraph", "Resumo parece ter mais de um parágrafo. Revise antes da versão final."); }
  if (hasValue(fields.palavrasChave)) { const i = keywordItems(fields.palavrasChave); if (i.length < 3 || i.length > 5) push(issues, "warning", "palavras-chave-count", `Palavras-chave com ${i.length} item(ns). Confira se há de 3 a 5 termos.`); if (i.length > 1 && !fields.palavrasChave.includes(";")) push(issues, "warning", "palavras-chave-separator", "Palavras-chave parecem não estar separadas por ponto e vírgula."); }
  if (hasValue(fields.abstractText)) { const c = wordCount(fields.abstractText); if (c < 150 || c > 500) push(issues, "warning", "abstract-word-count", `Abstract com ${c} palavra(s). Confira se está entre 150 e 500 palavras antes da versão final.`); if (paragraphCount(fields.abstractText) > 1) push(issues, "warning", "abstract-single-paragraph", "Abstract parece ter mais de um parágrafo. Revise antes da versão final."); }
  if (hasValue(fields.keywords)) { const i = keywordItems(fields.keywords); if (i.length < 3 || i.length > 5) push(issues, "warning", "keywords-count", `Keywords com ${i.length} item(ns). Confira se há de 3 a 5 termos.`); if (i.length > 1 && !fields.keywords.includes(";")) push(issues, "warning", "keywords-separator", "Keywords parecem não estar separadas por ponto e vírgula."); }
}

function addImpactIndicatorIssues(fields: AcademicFields, issues: ValidationIssue[]): void { if (fields.workType !== "dissertacao" && fields.workType !== "tese") return; const isInstructional = hasValue(fields.indicadoresImpacto) && detectPlaceholderText(fields.indicadoresImpacto); const sufficient = hasSufficientImpactIndicators(fields); if (!sufficient && !isInstructional) push(issues, "error", "impact-indicators-missing", "Preencha os Indicadores de Impacto antes da versão final.", "Os indicadores de impacto estão vazios ou insuficientes.", "A UFLA pode exigir indicadores de impacto em dissertações e teses; texto genérico não é aceitável.", "Preencha ao menos dois dos campos de impacto (social, científico, educacional, ambiental, tecnológico/econômico) e o público beneficiado com informações reais do trabalho."); if (isInstructional) push(issues, "error", "impact-indicators-missing", "Preencha os Indicadores de Impacto com informações reais antes da versão final.", "Os indicadores de impacto contêm apenas texto instrucional.", "A UFLA pode exigir indicadores de impacto em dissertações e teses; texto genérico não é aceitável.", "Substitua o texto instrucional por informações reais do trabalho."); if (hasValue(fields.indicadoresImpacto) && !isInstructional && !hasValue(fields.impactIndicators)) push(issues, "warning", "impact-indicators-english-recommended", "Inclua a versão em inglês dos indicadores de impacto quando exigida."); }
function looksInstitutionalAuthor(value: string): boolean { return /\b(UNIVERSIDADE|UFLA|INSTITUTO|PROGRAMA|POS-GRADUACAO|CURSO|DEPARTAMENTO|FACULDADE|ESCOLA|LAVRAS|MINAS GERAIS|MG)\b/.test(normalizeForValidation(value)); }
function hasLikelyImageWithoutCaption(text: string): boolean { return /!\[[^\]]*\]\(|<img\b|\bimagem\b|\[Imagem detectada:/i.test(text) && !/\b(figura|imagem)\s+\d+|\blegenda\b/i.test(text); }
function hasLikelyUnmarkedLongQuote(text: string): boolean { return text.split(/\n{2,}/).map((p) => p.trim()).some((p) => p.length > 450 && !p.startsWith(">") && /\([A-ZÁÉÍÓÚÂÊÔÃÕÇ][^)]*,\s*(19|20)\d{2}/.test(p)); }
function referenceIssueMessage(code: string, message: string): string { if (code === "reference-normative-preserved") return `${message} Isso pode estar correto para leis, portarias e resoluções, mas confira no Word antes da entrega.`; if (code === "reference-access-missing" || code === "reference-highlight-missing") return `${message} Revise antes da versão final.`; return message; }
function estimatePages(fields: AcademicFields, editorText: string): number { return Math.max(1, Math.ceil([fields.title, fields.author, fields.abstractText, fields.keywords, fields.resumo, fields.palavrasChave, editorText, fields.referencias].join("\n").length / 3200)); }
function estimateLineCount(value: string): number { return value.split(/\n+/).map((l) => l.trim()).filter(Boolean).reduce((total, line) => total + Math.max(1, Math.ceil(line.length / 95)), 0); }
function addCpgWarnings(fields: AcademicFields, editorText: string, issues: ValidationIssue[]): void { if (!isCpgWork(fields.workType)) return; push(issues, "warning", "cpg-mode-selected", "Modo CPG/UFLA selecionado: não use capa, folha de rosto, ficha catalográfica, folha de aprovação, indicadores de impacto, sumário, cabeçalho, rodapé ou número de página. A submissão final deve ser em PDF."); if (fields.workType === "resumo_cpg") push(issues, "warning", "cpg-resumo-one-page", "Resumo CPG/UFLA deve ter apenas 1 página, em português, A4, coluna simples, margens 3,5 cm superior, 2,5 cm inferior e 3 cm laterais."); if (fields.workType === "resumo_expandido_cpg") push(issues, "warning", "cpg-expanded-pages", "Resumo expandido CPG/UFLA deve ter de 4 a 6 páginas e conter abstract e resumo na primeira página."); if (fields.workType === "artigo_completo_cpg") push(issues, "warning", "cpg-full-pages", "Artigo completo CPG/UFLA deve ter de 8 a 14 páginas e conter abstract e resumo na primeira página."); const p = estimatePages(fields, editorText); if (fields.workType === "resumo_cpg" && p > 1) push(issues, "warning", "cpg-resumo-estimated-pages", `Estimativa atual: ${p} pagina(s). Para resumo CPG, ajuste o conteudo para 1 pagina.`); if (fields.workType === "resumo_expandido_cpg" && (p < 4 || p > 6)) push(issues, "warning", "cpg-expanded-estimated-pages", `Estimativa atual: ${p} página(s). Para resumo expandido CPG, ajuste para 4 a 6 páginas.`); if (fields.workType === "artigo_completo_cpg" && (p < 8 || p > 14)) push(issues, "warning", "cpg-full-estimated-pages", `Estimativa atual: ${p} página(s). Para artigo completo CPG, ajuste para 8 a 14 páginas.`); if (fields.workType !== "resumo_cpg" && estimateLineCount(fields.abstractText) > 10) push(issues, "warning", "cpg-abstract-too-long", "Abstract CPG parece ultrapassar 10 linhas. Encurte ou revise a primeira pagina antes da submissao."); if (fields.workType !== "resumo_cpg" && estimateLineCount(fields.resumo) > 10) push(issues, "warning", "cpg-resumo-too-long", "Resumo CPG parece ultrapassar 10 linhas. Encurte ou revise a primeira pagina antes da submissao."); if (/<table\b|<\/table>|!\[[^\]]*\]\(|<img\b|\[Imagem detectada:/i.test(editorText)) push(issues, "warning", "cpg-complex-media-warning", "Modelos CPG com imagens ou tabelas complexas precisam de conferencia visual: legendas, qualidade e espacamento podem exigir ajuste manual."); }
function addResearchProjectIssues(fields: AcademicFields, editorText: string, issues: ValidationIssue[]): void { if (!isResearchProject(fields.workType)) return; push(issues, "warning", "research-project-partial", "Suporte inicial para Projeto de pesquisa (NBR 15287:2025). A revisão final pelo usuário é obrigatória."); const checks: [boolean, string, string][] = [[hasValue(fields.problemaPesquisa) || hasSectionHeading(editorText, ["PROBLEMA DE PESQUISA", "PROBLEMA"]), "research-problem-required", "Informe o problema de pesquisa."], [hasValue(fields.objetivoGeral) || hasSectionHeading(editorText, ["OBJETIVO GERAL"]), "research-goal-required", "Informe o objetivo geral."], [hasValue(fields.justificativa) || hasSectionHeading(editorText, ["JUSTIFICATIVA"]), "research-justification-required", "Informe a justificativa."], [hasValue(fields.metodologia) || hasSectionHeading(editorText, ["METODOLOGIA", "PROCEDIMENTOS METODOLÓGICOS", "PROCEDIMENTOS METODOLOGICOS"]), "research-methodology-required", "Informe a metodologia."], [hasValue(fields.cronograma) || hasSectionHeading(editorText, ["CRONOGRAMA"]), "research-schedule-required", "Informe o cronograma."], [hasValue(fields.referencias) || hasSectionHeading(editorText, ["REFERÊNCIAS", "REFERENCIAS", "BIBLIOGRÁFICAS", "BIBLIOGRAFICAS"]), "research-references-required", "Informe as referências."]]; for (const [ok, code, msg] of checks) if (!ok) push(issues, "error", code, msg); }
function addUflaCollectionIssues(fields: AcademicFields, issues: ValidationIssue[]): void { if (!isUflaCollectionWork(fields.workType)) return; const t = academicProductionTypeById(fields.workType); if (!t) return; push(issues, "warning", "ufla-collection-initial-support", ACADEMIC_PRODUCTION_INITIAL_SUPPORT_NOTICE); for (const k of t.requiredFields) if (!hasValue(fields[k])) push(issues, "error", `ufla-collection-${k}-required`, `Preencha o campo obrigatorio para ${t.label}: ${k}.`); }

export function validateWork(fields: AcademicFields, editorText = ""): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  const simpleArticle = isSimpleArticle(fields);
  if (!hasValue(fields.workType)) push(issues, "error", "work-type-required", "Selecione o tipo de trabalho.", "O tipo de trabalho não foi informado.", "O tipo define quais elementos pré-textuais e regras de formatação serão aplicados no DOCX.", "Escolha artigo, monografia, dissertação, tese ou outro na lista suspensa.");
  if (!hasValue(fields.title)) push(issues, simpleArticle ? "warning" : "error", "title-required", simpleArticle ? "Título não detectado automaticamente; será usado título provisório no artigo simples." : "Informe o título do trabalho.");
  if (!hasValue(fields.author)) push(issues, "error", "author-required", "Informe o autor do trabalho."); else if (looksInstitutionalAuthor(fields.author)) push(issues, "error", "author-institutional", "O campo autor parece conter uma instituição, programa, unidade ou localidade, não um nome de pessoa. Revise a identificação automática.");
  if (!hasValue(fields.resumo)) push(issues, "warning", "resumo-required", "Inclua o resumo antes da versão final.");
  if (!hasValue(fields.referencias) && !isCpgWork(fields.workType)) push(issues, "warning", "references-required", "Inclua as referências do trabalho."); else if (hasValue(fields.referencias)) for (const r of validateReferencesText(fields.referencias)) push(issues, "warning", r.code, referenceIssueMessage(r.code, r.message));
  if (!hasValue(fields.introducao) && !isCpgWork(fields.workType) && !simpleArticle) push(issues, "warning", "intro-required", "A introdução não foi detectada ou está vazia.");
  if (!hasValue(fields.abstractText) && fields.workType !== "resumo_cpg" && !simpleArticle) push(issues, "warning", "abstract-recommended", "Inclua o abstract quando exigido pelo trabalho.");
  addCriticalMetadataIssues(fields, issues);
  addResumoAbstractIssues(fields, issues);
  addImpactIndicatorIssues(fields, issues);
  addCpgWarnings(fields, editorText, issues);
  addResearchProjectIssues(fields, editorText, issues);
  addUflaCollectionIssues(fields, issues);
  addPlaceholderIssues(fields, editorText, issues);
  addProgramConflictIssues(fields, editorText, issues);
  addAbstractTopicIssues(fields, issues);
  addGenericAiLikeIssues(fields, editorText, issues);
  addTextDiagnosticIssues(fields, issues);
  addCpgForbiddenIssues(fields, editorText, issues);
  if (hasLikelyImageWithoutCaption(editorText)) push(issues, "warning", "image-caption-warning", "Imagem detectada sem legenda provável. Confira posição, qualidade e legenda antes da versão final.");
  if (hasLikelyUnmarkedLongQuote(editorText)) push(issues, "warning", "long-quote-warning", "Há possível citação longa não marcada como citação longa. Revise antes da versão final.");
  if (hasValue(fields.imageWarnings)) push(issues, "warning", "imported-image-warning", `${fields.imageWarnings} A preservacao visual nao e garantida automaticamente.`);
  if (hasValue(fields.anexos) && /\[Imagem detectada:/i.test(fields.anexos)) push(issues, "warning", "annex-image-partial", "Há imagem detectada em anexos; confira posição, qualidade e legenda antes da versão final.");
  return issues;
}

export function hasBlockingErrors(issues: ValidationIssue[]): boolean { return issues.some((issue) => issue.severity === "error"); }
